// Shared asset paths — all local (public/assets/)
export const imgHeroMain      = '/assets/hero-main.jpg'
export const imgHeroImg95     = '/assets/hero-img95.png'
export const imgHeroImg96     = '/assets/hero-img96.png'
export const imgHeroImg97     = '/assets/hero-img97.png'
export const imgHeroImg98     = '/assets/hero-img98.png'
export const imgLogoIcon      = '/assets/logo-icon.svg'
export const imgQuizIcon      = '/assets/quiz-icon.svg'
export const imgNoObligIcon   = '/assets/no-obligation-icon.svg'
export const imgHipaaIcon     = '/assets/hipaa-icon.svg'

export const imgSymptomsBg    = '/assets/symptoms-bg.png'
export const imgSymptomsCenter= '/assets/symptoms-center.png'
export const imgEllipse14     = '/assets/ellipse14.svg'
export const imgEllipse16     = '/assets/ellipse16.svg'
export const imgDotIcon       = '/assets/dot-icon.svg'
export const imgSymptomIcon1  = '/assets/symptom-icon1.svg'
export const imgSymptomIcon2  = '/assets/symptom-icon2.svg'
export const imgSymptomIcon3  = '/assets/symptom-icon3.svg'
export const imgSymptomIcon4  = '/assets/symptom-icon4.svg'
export const imgSymptomVector = '/assets/symptom-vector.svg'
export const imgSymptomIcon5  = '/assets/symptom-icon5.svg'

export const imgPhone         = '/assets/phone.png'
export const imgAppScreen     = '/assets/app-screen.png'
export const imgConsult       = '/assets/consult.png'
export const imgRect51        = '/assets/rect51.png'
export const imgPlan          = '/assets/plan.png'

export const imgQuoteDecor    = '/assets/quote-decor.svg'
export const imgProviderMask  = '/assets/provider-mask.svg'
export const imgProviderPhoto = '/assets/provider-photo.jpg'
export const imgProviderOverlay = '/assets/provider-overlay.png'
export const imgCredentials1  = '/assets/credentials1.svg'
export const imgCredentials2  = '/assets/credentials2.svg'
export const imgCredentials3  = '/assets/credentials3.svg'

export const imgQuoteIcon     = '/assets/quote-icon.svg'
export const imgAvatarDenise  = '/assets/avatar-denise.png'
export const imgAvatarRina    = '/assets/avatar-rina.png'
export const imgAvatarDella   = '/assets/avatar-della.png'

export const imgFaqArrow      = '/assets/faq-arrow.svg'
export const imgFaqLine       = '/assets/faq-line.svg'

export const imgCtaBg         = '/assets/cta-bg.jpg'
export const imgCtaCouple     = '/assets/cta-couple.png'

export const imgFooterIcon    = '/assets/footer-icon.svg'
export const imgSocialIcons   = '/assets/social-icons.svg'

// Hormones Landing Page
export const imgHormonesHero1       = '/assets/hormones-hero1.jpg'
export const imgHormonesHero2       = '/assets/hormones-hero2.jpg'
export const imgHormonesHero3       = '/assets/hormones-hero3.jpg'
export const imgHormonesHero4       = '/assets/hormones-hero4.jpg'
export const imgHormonesHero5       = '/assets/hormones-hero5.jpg'
export const imgHormonesSymptomsBg  = '/assets/hormones-symptoms-bg.png'
export const imgHormonesCenter      = '/assets/hormones-symptoms-center.png'
export const imgHormonesIcon1       = '/assets/hormones-icon1.svg'
export const imgHormonesIcon2       = '/assets/hormones-icon2.svg'
export const imgHormonesIcon3       = '/assets/hormones-icon3.svg'
export const imgHormonesIcon4       = '/assets/hormones-icon4.svg'
export const imgHormonesIcon5       = '/assets/hormones-icon5.svg'
export const imgHormonesIcon6       = '/assets/hormones-icon6.svg'
export const imgHormonesCtaBg       = '/assets/hormones-cta-bg.jpg'
export const imgHormonesStep3       = '/assets/hormones-step3.jpg'

// Digestive Landing Page
export const imgDigestiveHero1      = '/assets/digestive-hero1.jpg'
export const imgDigestiveHero2      = '/assets/digestive-hero2.jpg'
export const imgDigestiveHero3      = '/assets/digestive-hero3.jpg'
export const imgDigestiveHero4      = '/assets/digestive-hero4.jpg'
export const imgDigestiveHero5      = '/assets/digestive-hero5.jpg'
export const imgDigestiveSymptomsBg = '/assets/digestive-symptoms-bg.png'
export const imgDigestiveCenter     = '/assets/digestive-symptoms-center.png'
export const imgDigestiveIcon1      = '/assets/digestive-icon1.svg'
export const imgDigestiveIcon2      = '/assets/digestive-icon2.svg'
export const imgDigestiveIcon3      = '/assets/digestive-icon3.svg'
export const imgDigestiveIcon4      = '/assets/digestive-icon4.svg'
export const imgDigestiveIcon5      = '/assets/digestive-icon5.svg'
export const imgDigestiveIcon6      = '/assets/digestive-icon6.svg'
export const imgDigestiveStep3      = '/assets/digestive-step3.jpg'
export const imgDigestiveCtaBg      = '/assets/digestive-cta-bg.jpg'

// Form / Quiz — Welcome
export const imgFormWelcomePhoto  = '/assets/form-welcome-photo.jpg'
export const imgFormDecorIcon     = '/assets/form-decor-icon.svg'
export const imgFormPhotoMask     = '/assets/form-photo-mask.svg'

// Form / Quiz — Q2 (Age)
export const imgFormQ2Thumb         = '/assets/form-q2-thumb.svg'

// Form / Quiz — Q1 (Gender)
export const imgFormQ1SelectedCheck = '/assets/form-q1-selected-check.svg'
export const imgFormQ1MaleSymbol    = '/assets/form-q1-male-symbol.svg'
export const imgFormQ1FemaleSymbol  = '/assets/form-q1-female-symbol.svg'
export const imgFormQ1NbMask        = '/assets/form-q1-nb-mask.svg'
export const imgFormQ1NbSymbol      = '/assets/form-q1-nb-symbol.svg'
export const imgFormQ1NoSymbol      = '/assets/form-q1-no-symbol.svg'
